from src.model import Route, Colour, Card

cards = []
for colour, times in [(Colour.PINK, 12), (Colour.WHITE, 12), (Colour.BLUE, 12),
 (Colour.YELLOW, 12), (Colour.ORANGE, 12), (Colour.BLACK, 12), (Colour.RED, 12),
 (Colour.GREEN, 12), (Colour.ANY, 14)]:
      for _ in range(times):
        cards.append(Card(colour))
routes = [Route('Vancouver', 'Calgary', 3, Colour.ANY),
          Route('Vancouver', 'Seattle', 1, Colour.ANY),
          Route('Vancouver', 'Seattle', 1, Colour.ANY),
          Route('Seattle', 'Calgary', 4, Colour.ANY),
          Route('Seattle', 'Portland', 1, Colour.ANY),
          Route('Seattle', 'Portland', 1, Colour.ANY),
          Route('Seattle', 'Helena', 6, Colour.YELLOW),
          Route('Calgary', 'Helena', 4, Colour.ANY),
          Route('Calgary', 'Winnipeg', 6, Colour.WHITE),
          Route('Calgary', 'Helena', 4, Colour.BLUE),
          Route('Winnipeg', 'Sault St Marie', 6, Colour.ANY),
          Route('Winnipeg', 'Duluth', 4, Colour.BLACK),
          Route('Duluth', 'Sault St Marie', 3, Colour.ANY),
          Route('Duluth', 'Helena', 6, Colour.ORANGE),
          Route('Sault St Marie', 'Montreal', 5, Colour.BLACK),
          Route('Montreal', 'Boston', 2, Colour.ANY),
          Route('Montreal', 'Boston', 2, Colour.ANY),
          Route('Montreal', 'Toronto', 3, Colour.ANY),
          Route('Sault St Marie', 'Toronto', 2, Colour.ANY),
          Route('Duluth', 'Toronto', 6, Colour.PINK),
          Route('Montreal', 'New York', 3, Colour.BLUE),
          Route('Boston', 'New York', 2, Colour.YELLOW),
          Route('Boston', 'New York', 2, Colour.RED),
          Route('New York', 'Pittsburgh', 2, Colour.WHITE),
          Route('New York', 'Pittsburgh', 2, Colour.GREEN),
          Route('Toronto', 'Pittsburgh', 2, Colour.ANY),
          Route('New York', 'Washington', 2, Colour.ORANGE),
          Route('New York', 'Washington', 2, Colour.BLACK),
          Route('Pittsburgh', 'Washington', 2, Colour.ANY),
          Route('Pittsburgh', 'Raleigh', 2, Colour.ANY),
          Route('Washington', 'Raleigh', 2, Colour.ANY),
          Route('Washington', 'Raleigh', 2, Colour.ANY),
          Route('Raleigh', 'Charleston', 2, Colour.ANY),
          Route('Charleston', 'Miami', 4, Colour.PINK),
          Route('Atlanta', 'Miami', 5, Colour.BLUE),
          Route('New Orleans', 'Miami', 6, Colour.ORANGE),
          Route('Atlanta', 'Charleston', 2, Colour.ANY),
          Route('Raleigh', 'Atlanta', 2, Colour.ANY),
          Route('Raleigh', 'Atlanta', 2, Colour.ANY),
          Route('New Orleans', 'Atlanta', 4, Colour.ORANGE),
          Route('New Orleans', 'Atlanta', 4, Colour.YELLOW),
          Route('Nashville', 'Atlanta', 1, Colour.ANY),
          Route('Little Rock', 'New Orleans', 3, Colour.GREEN),
          Route('Houston', 'New Orleans', 2, Colour.ANY),
          Route('Nashville', 'Little Rock', 3, Colour.WHITE),
          Route('Nashville', 'Raleigh', 3, Colour.BLACK),
          Route('Nashville', 'Saint Louis', 2, Colour.ANY),
          Route('Pittsburgh', 'Nashville', 4, Colour.YELLOW),
          Route('Pittsburgh', 'Saint Louis', 5, Colour.GREEN),
          Route('Chicago', 'Pittsburgh', 3, Colour.ORANGE),
          Route('Chicago', 'Pittsburgh', 3, Colour.BLACK),
          Route('Chicago', 'Toronto', 4, Colour.WHITE),
          Route('Chicago', 'Duluth', 3, Colour.RED),
          Route('Chicago', 'Saint Louis', 2, Colour.GREEN),
          Route('Chicago', 'Saint Louis', 2, Colour.WHITE),
          Route('Chicago', 'Omaha', 4, Colour.BLUE),
          Route('Denver', 'Omaha', 4, Colour.PINK),
          Route('Denver', 'Helena', 4, Colour.GREEN),
          Route('Omaha', 'Helena', 5, Colour.RED),
          Route('Omaha', 'Duluth', 2, Colour.ANY),
          Route('Omaha', 'Duluth', 2, Colour.ANY),
          Route('Denver', 'Kansas City', 4, Colour.BLACK),
          Route('Denver', 'Kansas City', 4, Colour.ORANGE),
          Route('Omaha', 'Kansas City', 1, Colour.ANY),
          Route('Omaha', 'Kansas City', 1, Colour.ANY),
          Route('Saint Louis', 'Kansas City', 2, Colour.BLUE),
          Route('Saint Louis', 'Kansas City', 2, Colour.PINK),
          Route('Saint Louis', 'Little Rock', 2, Colour.ANY),
          Route('Denver', 'Oklahoma City', 4, Colour.RED),
          Route('Oklahoma City', 'Kansas City', 2, Colour.ANY),
          Route('Oklahoma City', 'Kansas City', 2, Colour.ANY),
          Route('Oklahoma City', 'Little Rock', 2, Colour.ANY),
          Route('Denver', 'Santa Fe', 2, Colour.ANY),
          Route('El Paso', 'Santa Fe', 2, Colour.ANY),
          Route('Oklahoma City', 'Santa Fe', 3, Colour.BLUE),
          Route('Oklahoma City', 'El Paso', 5, Colour.YELLOW),
          Route('El Paso', 'Houston', 6, Colour.GREEN),
          Route('El Paso', 'Dallas', 4, Colour.RED),
          Route('Oklahoma City', 'Dallas', 2, Colour.ANY),
          Route('Oklahoma City', 'Dallas', 2, Colour.ANY),
          Route('Little Rock', 'Dallas', 2, Colour.ANY),
          Route('Houston', 'Dallas', 1, Colour.ANY),
          Route('Houston', 'Dallas', 1, Colour.ANY),
          Route('El Paso', 'Phoenix', 3, Colour.ANY),
          Route('Phoenix', 'Santa Fe', 3, Colour.ANY),
          Route('El Paso', 'Los Angeles', 6, Colour.BLACK),
          Route('Phoenix', 'Los Angeles', 3, Colour.ANY),
          Route('Las Vegas', 'Los Angeles', 2, Colour.ANY),
          Route('Denver', 'Phoenix', 5, Colour.WHITE),
          Route('Salt Lake City', 'Helena', 3, Colour.PINK),
          Route('Salt Lake City', 'Denver', 3, Colour.RED),
          Route('Salt Lake City', 'Denver', 3, Colour.YELLOW),
          Route('Salt Lake City', 'Las Vegas', 3, Colour.ORANGE),
          Route('Salt Lake City', 'Portland', 6, Colour.BLUE),
          Route('San Francisco', 'Portland', 5, Colour.PINK),
          Route('San Francisco', 'Portland', 5, Colour.GREEN),
          Route('San Francisco', 'Salt Lake City', 5, Colour.ORANGE),
          Route('San Francisco', 'Salt Lake City', 5, Colour.WHITE),
          Route('San Francisco', 'Los Angeles', 3, Colour.PINK),
          Route('San Francisco', 'Los Angeles', 3, Colour.YELLOW)]